image: docker:latest

before_script:
  - docker info
  - docker -v
  - apk add --no-cache python3 git
  - python3 --version
  - wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm *.py
  - pip3 --version
  - pip3 install --upgrade git+https://github.com/rapydo/utils.git@0.6.0
  - pip3 install --upgrade git+https://github.com/rapydo/do.git@0.6.0
  - rapydo --version
  - docker-compose -v
  - git status


job:
  script:
    - mkdir data

    - docker rmi $(docker images | grep "^imc/" | awk {'print $3'})
    - rapydo --project imc clean
    
    - rapydo --project imc init --skip-bower
    - rapydo --project imc start
    - rapydo --project imc remove
    - ls data/

    # - rapydo --project imc test
    
  # only:
  #   - NO_ONE