image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - docker info
  - docker -v
  - apk add --no-cache python3 git
  - python3 --version
  - wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm *.py
  - pip3 --version
  - pip3 install --upgrade git+https://github.com/rapydo/utils.git@0.6.1
  - pip3 install --upgrade git+https://github.com/rapydo/do.git@0.6.1
  - rapydo --version
  - docker-compose -v
  - git status


job:
  script:
    - mkdir data

    - rapydo --project imc init --skip-bower
    - rapydo --project imc clean
    - rapydo --project imc build -rf
    
    - rapydo --project imc start
    - rapydo --project imc remove
    - ls data/

    # - rapydo --project imc test
    
  only:
    - 0.6.1
