image: docker:latest

before_script:
  - docker info
  - docker -v
  - apk add --no-cache python3 git
  - python3 --version
  - wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm *.py
  - pip3 --version
  - pip3 install rapydo-controller
  - rapydo --version
  - docker-compose -v


job:
  script:

    - rapydo --project imc --mode production init
    - rapydo --project imc --mode production start

    # - rapydo --project imc --mode production test
    
  # only:
  #   - NO_ONE