---
project:
  title: My Neo4j project
  description: Title of my Neo4j project
  version: "RAPyDo framework v0.5.5-beta"

variables:
  repos:
    rapydo:
      branch: 0.5.5
    utils:
      branch: 0.5.5
    backend:
      branch: 0.5.5
    build-templates:
      branch: 0.5.5
  env:
    GRAPHDB_PASSWORD: chooseapassword
    IRODS_CHUNKSIZE: 1048576
  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user
  frontend:
    enable: true

