# -*- coding: utf-8 -*-

concept_mapping = {}
concept_mapping['person']         = 'https://www.wikidata.org/wiki/Q5'        # 1
concept_mapping['bicycle']        = 'https://www.wikidata.org/wiki/Q11442'    # 2
concept_mapping['car']            = 'https://www.wikidata.org/wiki/Q1420'     # 3
concept_mapping['motorbike']      = 'https://www.wikidata.org/wiki/Q34493'    # 4
concept_mapping['aeroplane']      = 'https://www.wikidata.org/wiki/Q197'      # 5
concept_mapping['bus']            = 'https://www.wikidata.org/wiki/Q5638'     # 6
concept_mapping['train']          = 'https://www.wikidata.org/wiki/Q870'      # 7
concept_mapping['truck']          = 'https://www.wikidata.org/wiki/Q43193'    # 8
concept_mapping['boat']           = 'https://www.wikidata.org/wiki/Q11446'    # 9
concept_mapping['traffic light']  = 'https://www.wikidata.org/wiki/Q8004'     # 10
concept_mapping['fire hydrant']   = 'https://www.wikidata.org/wiki/Q634299'   # 11
concept_mapping['stop sign']      = 'https://www.wikidata.org/wiki/Q170285'   # 12
concept_mapping['parking meter']  = 'https://www.wikidata.org/wiki/Q953960'   # 13
concept_mapping['bench']          = 'https://www.wikidata.org/wiki/Q204776'   # 14
concept_mapping['bird']           = 'https://www.wikidata.org/wiki/Q5113'     # 15
concept_mapping['cat']            = 'https://www.wikidata.org/wiki/Q146'      # 16
concept_mapping['dog']            = 'https://www.wikidata.org/wiki/Q144'      # 17
concept_mapping['horse']          = 'https://www.wikidata.org/wiki/Q726'      # 18
concept_mapping['sheep']          = 'https://www.wikidata.org/wiki/Q7368'     # 19
concept_mapping['cow']            = 'https://www.wikidata.org/wiki/Q830'      # 20
concept_mapping['elephant']       = 'https://www.wikidata.org/wiki/Q7378'     # 21
concept_mapping['bear']           = 'https://www.wikidata.org/wiki/Q1019010'  # 22
concept_mapping['zebra']          = 'https://www.wikidata.org/wiki/Q32789'    # 23
concept_mapping['giraffe']        = 'https://www.wikidata.org/wiki/Q15083'    # 24
concept_mapping['backpack']       = 'https://www.wikidata.org/wiki/Q5843'     # 25
concept_mapping['umbrella']       = 'https://www.wikidata.org/wiki/Q41607'    # 26
concept_mapping['handbag']        = 'https://www.wikidata.org/wiki/Q467505'   # 27
concept_mapping['tie']            = 'https://www.wikidata.org/wiki/Q44416'    # 28
concept_mapping['suitcase']       = 'https://www.wikidata.org/wiki/Q200814'   # 29
concept_mapping['frisbee']        = 'https://www.wikidata.org/wiki/Q131689'   # 30
concept_mapping['skis']           = 'https://www.wikidata.org/wiki/Q172226'   # 31
concept_mapping['snowboard']      = 'https://www.wikidata.org/wiki/Q2000617'  # 32
concept_mapping['sports ball']    = 'https://www.wikidata.org/wiki/Q18545'    # 33
concept_mapping['kite']           = 'https://www.wikidata.org/wiki/Q42861'    # 34
concept_mapping['baseball bat']   = 'https://www.wikidata.org/wiki/Q809910'   # 35
concept_mapping['baseball glove'] = 'https://www.wikidata.org/wiki/Q809894'   # 36
concept_mapping['skateboard']     = 'https://www.wikidata.org/wiki/Q15783'    # 37
concept_mapping['surfboard']      = 'https://www.wikidata.org/wiki/Q457689'   # 38
concept_mapping['tennis racket']  = 'https://www.wikidata.org/wiki/Q153362'   # 39
concept_mapping['bottle']         = 'https://www.wikidata.org/wiki/Q80228'    # 40
concept_mapping['wine glass']     = 'https://www.wikidata.org/wiki/Q81727'    # 41
concept_mapping['cup']            = 'https://www.wikidata.org/wiki/Q2100893'  # 42
concept_mapping['fork']           = 'https://www.wikidata.org/wiki/Q81881'    # 43
concept_mapping['knife']          = 'https://www.wikidata.org/wiki/Q32489'    # 44
concept_mapping['spoon']          = 'https://www.wikidata.org/wiki/Q81895'    # 45
concept_mapping['bowl']           = 'https://www.wikidata.org/wiki/Q153988'   # 46
concept_mapping['banana']         = 'https://www.wikidata.org/wiki/Q503'      # 47
concept_mapping['apple']          = 'https://www.wikidata.org/wiki/Q89'       # 48
concept_mapping['sandwich']       = 'https://www.wikidata.org/wiki/Q28803'    # 49
concept_mapping['orange']         = 'https://www.wikidata.org/wiki/Q13191'    # 50
concept_mapping['broccoli']       = 'https://www.wikidata.org/wiki/Q47722'    # 51
concept_mapping['carrot']         = 'https://www.wikidata.org/wiki/Q81'       # 52
concept_mapping['hot dog']        = 'https://www.wikidata.org/wiki/Q181055'   # 53
concept_mapping['pizza']          = 'https://www.wikidata.org/wiki/Q177'      # 54
concept_mapping['donut']          = 'https://www.wikidata.org/wiki/Q192783'   # 55
concept_mapping['cake']           = 'https://www.wikidata.org/wiki/Q13276'    # 56
concept_mapping['chair']          = 'https://www.wikidata.org/wiki/Q15026'    # 57
concept_mapping['sofa']           = 'https://www.wikidata.org/wiki/Q131514'   # 58
concept_mapping['pottedplant']    = 'https://www.wikidata.org/wiki/Q1369438'  # 59
concept_mapping['bed']            = 'https://www.wikidata.org/wiki/Q42177'    # 60
concept_mapping['diningtable']    = 'https://www.wikidata.org/wiki/Q14748'    # 61
concept_mapping['toilet']         = 'https://www.wikidata.org/wiki/Q7857'     # 62
concept_mapping['tvmonitor']      = 'https://www.wikidata.org/wiki/Q289'      # 63
concept_mapping['laptop']         = 'https://www.wikidata.org/wiki/Q3962'     # 64
concept_mapping['mouse']          = 'https://www.wikidata.org/wiki/Q7987'     # 65
concept_mapping['remote']         = 'https://www.wikidata.org/wiki/Q185091'   # 66
concept_mapping['keyboard']       = 'https://www.wikidata.org/wiki/Q250'      # 67
concept_mapping['cell phone']     = 'https://www.wikidata.org/wiki/Q17517'    # 68
concept_mapping['microwave']      = 'https://www.wikidata.org/wiki/Q127956'   # 69
concept_mapping['oven']           = 'https://www.wikidata.org/wiki/Q36539'    # 70
concept_mapping['toaster']        = 'https://www.wikidata.org/wiki/Q14890'    # 71
concept_mapping['sink']           = 'https://www.wikidata.org/wiki/Q140565'   # 72
concept_mapping['refrigerator']   = 'https://www.wikidata.org/wiki/Q37828'    # 73
concept_mapping['book']           = 'https://www.wikidata.org/wiki/Q571'      # 74
concept_mapping['clock']          = 'https://www.wikidata.org/wiki/Q376'      # 75
concept_mapping['vase']           = 'https://www.wikidata.org/wiki/Q191851'   # 76
concept_mapping['scissors']       = 'https://www.wikidata.org/wiki/Q40847'    # 77
concept_mapping['teddy bear']     = 'https://www.wikidata.org/wiki/Q213477'   # 78
concept_mapping['hair drier']     = 'https://www.wikidata.org/wiki/Q15004'    # 79
concept_mapping['toothbrush']     = ' https://www.wikidata.org/wiki/Q134205'  # 80
