project:
  title: "I-Media-Cities"
  description: "Innovative e-Environment for Research on Cities and the Media"
  version: "1.9.3"
  rapydo: "1.2"

variables:
  env:
    FRONTEND_FRAMEWORK: angular
    ENABLE_FOOTER: 0
    CORS_ALLOWED_ORIGIN: "*"

    AUTH_SERVICE: neo4j
    AUTH_TOKEN_IP_GRACE_PERIOD: 2592000
    SET_MAX_REQUESTS_PER_SECOND_API: 30

    ACTIVATE_FTP: 1
    ACTIVATE_CELERY: 1
    # Temporary fix
    ACTIVATE_CELERYUI: 0
    ACTIVATE_NEO4J: 1
    ACTIVATE_REDIS: 1
    ACTIVATE_RABBIT: 1
    CELERY_ENABLE_CONNECTOR: 1

    ALLOW_ACCESS_TOKEN_PARAMETER: 1
    ALLOW_PASSWORD_RESET: 1
    ALLOW_REGISTRATION: 1
    ALLOW_TERMS_OF_USE: 1
    ENABLE_ANGULAR_SSR: 0

    GRAPHDB_PASSWORD: "**PLACEHOLDER**"
    GMAP_KEY: "**PLACEHOLDER**"
    VIRTUAL_GALLERY_URL: "**PLACEHOLDER**"
    SMTP_ADMIN: "**PLACEHOLDER**"
    SMTP_NOREPLY: "**PLACEHOLDER**"
    SMTP_HOST: "**PLACEHOLDER**"

    CELERY_BACKEND: REDIS

    SET_CSP_SCRIPT_SRC: "https://maps.google.com https://maps.googleapis.com https://www.wikidata.org"
    SET_CSP_IMG_SRC: "https://maps.google.com https://maps.gstatic.com"

    FRONTEND_LANG: "en"
    FRONTEND_DISABLED_FILTERS: ""
    CATALOG_TIME_RANGE_FROM: "1890"
    CATALOG_TIME_RANGE_TO: "1999"

  roles:
    normal_user: User
    staff_user: Staff
    # group_coordinator: Coordinator
    admin_root: Admin
    Archive: Archive
    Reviser: Reviser
    Researcher: Researcher
    read_only: ReadOnly
    # default: normal_user
    # allowed_roles:
    #   - Researcher
    #   - Archive
    #   - Reviser
    #   - normal_user

tags:
  file: "All endpoints to handle files"
  admin: "Operations only allowed for admin users"
  miscellaneous: "Endpoints not classified in other specific sections"

controller:
  commands:
    ftp-useradd:
      description: Create FTP credentials
      name: ftp
      command: echo 'Not implemented -> pure-pw useradd user@email.org -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/group-uuid'
      service: ftp
      user: root
    ftp-userdel:
      description: Delete FTP credentials
      name: ftp
      command: echo 'Not implemented -> pure-pw userdel user@email.org -f /etc/pure-ftpd/passwd/pureftpd.passwd -m'
      service: ftp
      user: root
