project:
    title: "iMediaCities Repository"
    description": "..."
    version: "1.1"
    rapydo: "0.5.6"
tags:
    file: "All endpoints to handle files"
    admin: "Operations only allowed for admin users"
    miscellaneous: "Endpoints not classified in other specific sections"

releases:
  '1.0':
    type: beta
    rapydo: 0.5.5
    status: released
  '1.1':
    type: beta
    rapydo: 0.5.6
    status: developing

variables:
  # repos:
  #   rapydo:
  #     branch: master
  #   utils:
  #     branch: master
  #   backend:
  #     branch: master
  #   build-templates:
  #     branch: master

  env:
    COMPOSE_PROJECT_NAME: imc
    PROJECT_DOMAIN: imediacities.hpc.cineca.it
    LETSENCRYPT_MODE: 
  
    # AUTH_REGISTER_FAILED_LOGIN: False
    # AUTH_FORCE_FIRST_PASSWORD_CHANGE: False
    # AUTH_VERIFY_PASSWORD_STRENGTH: False
    # AUTH_MAX_PASSWORD_VALIDITY: 0
    # AUTH_DISABLE_UNUSED_CREDENTIALS_AFTER: 0
    # AUTH_MAX_LOGIN_ATTEMPTS: 0
    # AUTH_SECOND_FACTOR_AUTHENTICATION: TOTP

    GRAPHDB_PASSWORD: chooseapassword

  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: "normal_user"
        internal: "staff_user"
        admin: "admin_root"
        default: "normal_user"
  frontend:
      enable: true
bower_components:
  ng-flow:
    - "dist/ng-flow-standalone.min.js"
  angular-tablesort:
    - js/angular-tablesort.js
    - tablesort.css
  ngmap:
    - build/scripts/ng-map.min.js
  angular-google-chart:
    - "ng-google-chart.min.js"

css: 
  - "custom/imc/search.css"
