project:
  title: "iMediaCities Repository"
  description: "..."
  version: "1.9.0"
  rapydo: "0.9"

variables:
  env:
    FRONTEND_FRAMEWORK: angular

    AUTH_SERVICE: neo4j

    ACTIVATE_FTP: 1
    ACTIVATE_CELERY: 1
    ACTIVATE_CELERYUI: 1
    ACTIVATE_NEO4J: 1
    ACTIVATE_MONGODB: 1
    ACTIVATE_RABBIT: 1

    ALLOW_ACCESS_TOKEN_PARAMETER: True
    ALLOW_PASSWORD_RESET: "true"
    ALLOW_REGISTRATION: "true"
    ALLOW_TERMS_OF_USE: "true"

    GRAPHDB_PASSWORD: "**PLACEHOLDER**"
    GMAP_KEY: "**PLACEHOLDER**"
    VIRTUAL_GALLERY_URL: "**PLACEHOLDER**"
    SMTP_ADMIN: "**PLACEHOLDER**"
    SMTP_NOREPLY: "**PLACEHOLDER**"
    SMTP_HOST: "**PLACEHOLDER**"

    CELERY_BACKEND: MONGODB

    SET_CSP_SCRIPT_SRC: "https://maps.google.com https://maps.googleapis.com https://www.wikidata.org"
    SET_CSP_IMG_SRC: "https://maps.google.com https://maps.gstatic.com"

    FRONTEND_LANG: "en"
    FRONTEND_DISABLED_FILTERS: ""

  roles:
    normal_user: User
    staff_user: Staff
    # group_coordinator: Coordinator
    admin_root: Admin
    Archive: Archive
    Reviser: Reviser
    Researcher: Researcher
    # default: normal_user
    # allowed_roles:
    #   - Researcher
    #   - Archive
    #   - Reviser
    #   - normal_user

tags:
  file: "All endpoints to handle files"
  admin: "Operations only allowed for admin users"
  miscellaneous: "Endpoints not classified in other specific sections"

controller:
  commands:
    ftp-useradd:
      description: Create FTP credentials
      name: ftp
      command: echo 'Not implemented -> pure-pw useradd user@email.org -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/group-uuid'
      service: ftp
      user: root
    ftp-userdel:
      description: Delete FTP credentials
      name: ftp
      command: echo 'Not implemented -> pure-pw userdel user@email.org -f /etc/pure-ftpd/passwd/pureftpd.passwd -m'
      service: ftp
      user: root
