project:
    title: "iMediaCities Repository"
    description": "..."
    version: "1.4.1"
tags:
    file: "All endpoints to handle files"
    admin: "Operations only allowed for admin users"
    miscellaneous: "Endpoints not classified in other specific sections"

releases:
  '1.1.0':
    type: beta
    rapydo: 0.5.5
    status: discontinued
  '1.1.1':
    type: beta
    rapydo: 0.5.7
    status: released
  '1.1.2':
    type: beta
    rapydo: 0.6.0
    status: discontinued 
  '1.2.0':
    type: beta
    rapydo: 0.5.7
    status: released 
  '1.2.1':
    type: beta
    rapydo: 0.6.0
    status: discontinued 
  '1.2.2':
    type: beta
    rapydo: 0.6.1
    status: discontinued
  '1.3.0':
    type: beta
    rapydo: 0.6.0
    status: released 
  '1.4.0':
    type: beta
    rapydo: 0.6.1
    status: developing
  '1.4.1':
    type: beta
    rapydo: 0.6.2
    status: developing

variables:
  repos:
    frontend:
      branch: 0.6.2

  env:
    COMPOSE_PROJECT_NAME: imc
    PROJECT_DOMAIN: imediacities.hpc.cineca.it
    LETSENCRYPT_MODE: 
  
    # AUTH_REGISTER_FAILED_LOGIN: False
    # AUTH_FORCE_FIRST_PASSWORD_CHANGE: False
    # AUTH_VERIFY_PASSWORD_STRENGTH: False
    # AUTH_MAX_PASSWORD_VALIDITY: 0
    # AUTH_DISABLE_UNUSED_CREDENTIALS_AFTER: 0
    # AUTH_MAX_LOGIN_ATTEMPTS: 0
    # AUTH_SECOND_FACTOR_AUTHENTICATION: TOTP

    GRAPHDB_PASSWORD: chooseapassword

    SMTP_ADMIN: m.dantonio@cineca.it
    SMTP_NOREPLY: I-Media-Cities@cinematek.be
    SMTP_HOST: mail.cineca.it
    SMTP_PORT: 587
    SMTP_USERNAME: hpc-service-noreply@cineca.it
    SMTP_PASSWORD: dnt%01u

  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: "normal_user"
        internal: "staff_user"
        admin: "admin_root"
        default: "normal_user"
    allowed_roles:
      - Researcher
      - Archive
  frontend:
      enable: true
bower_components:
  ng-flow:
    - "dist/ng-flow-standalone.min.js"
  angular-tablesort:
    - js/angular-tablesort.js
    - tablesort.css
  ngmap:
    - build/scripts/ng-map.min.js
  angular-google-chart:
    - "ng-google-chart.min.js"
  font-awesome:
    - css/font-awesome.min.css
  lodash:
    - dist/lodash.min.js
  angular-file-saver:
    - dist/angular-file-saver.bundle.min.js
  angular-ivh-treeview:
    - dist/ivh-treeview.min.js
    - dist/ivh-treeview.min.css
  ng-tags-input:
    - ng-tags-input.min.css
    - ng-tags-input.min.js
  google-marker-cluster:
    - markerclusterer.js
  angular-holderjs:
    - src/holder.js
  holderjs:
    - holder.min.js

css: 
  - "custom/imc.css"
  - "custom/VideoPlayer_stile.css"
