project:
    title: "iMediaCities Repository"
    description": "..."
    version: "1.4.2"
    rapydo: 0.6.2

variables:

  frontend:
    framework: angular

  # repos:
  #   frontend:
  #     online_url: https://github.com/rapydo/rapydo-angular.git
  #     branch: 0.6.2

  env:
    COMPOSE_PROJECT_NAME: imc
    PROJECT_DOMAIN: imediacities.hpc.cineca.it
    LETSENCRYPT_MODE: 
  
    ACTIVATE_FTP: 1
    ACTIVATE_CELERY: 1

    # AUTH_REGISTER_FAILED_LOGIN: False
    # AUTH_FORCE_FIRST_PASSWORD_CHANGE: False
    # AUTH_VERIFY_PASSWORD_STRENGTH: False
    # AUTH_MAX_PASSWORD_VALIDITY: 0
    # AUTH_DISABLE_UNUSED_CREDENTIALS_AFTER: 0
    # AUTH_MAX_LOGIN_ATTEMPTS: 0
    # AUTH_SECOND_FACTOR_AUTHENTICATION: TOTP

    GRAPHDB_PASSWORD: chooseapassword

    SMTP_ADMIN: m.dantonio@cineca.it
    SMTP_NOREPLY: I-Media-Cities@cinematek.be
    SMTP_HOST: mail.cineca.it
    SMTP_PORT: 587
    SMTP_USERNAME: hpc-service-noreply@cineca.it
    SMTP_PASSWORD: dnt%01u

  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: "normal_user"
        internal: "staff_user"
        admin: "admin_root"
        default: "normal_user"
    allowed_roles:
      - Researcher
      - Archive

tags:
    file: "All endpoints to handle files"
    admin: "Operations only allowed for admin users"
    miscellaneous: "Endpoints not classified in other specific sections"