# Customize this file to include compose configurations common to bluprints
version: '3'

services:
  backend:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${VANILLA_DIR}/scripts:/code/scripts
    networks:
      ftp_net:

  neo4j:
    restart: on-failure:5
    volumes:
      - ${VANILLA_DIR}/data/graphdata:/data
    ports:
      - 7687:7687
    # environment:
    #   NEO4J_dbms_memory_pagecache_size: 1024M
    #   NEO4J_dbms_memory_heap_maxSize: 2048M
    #   NEO4J_dbms_allowFormatMigration: "true"

  rabbit:
    expose:
      - "15672"
    ports:
      -  15672:15672

  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${SUBMODULE_DIR}/imedia-pipeline:/imedia-pipeline
      - /opt/idmt:/opt/idmt
      - ${VANILLA_DIR}/scripts:/code/scripts
      - ${VANILLA_DIR}/data/ssh:/home/developer/.ssh

    environment:
      # Used to manage analysis script on both prod and pre-prod
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}

  celeryui:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${VANILLA_DIR}/scripts:/code/scripts
      - ${VANILLA_DIR}/data/flower_db:${CELERYUI_DBDIR}

  ftp:
    ports:
      - "21:21"
      - "30000-30019:30000-30019"
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/home/ftpusers/
      - ${VANILLA_DIR}/data/ftp:/etc/pure-ftpd/passwd

  frontend:
    environment:
      ALLOW_PASSWORD_RESET: "true"
      ALLOW_REGISTRATION: "true"
      INJECT_GMAP_KEY: ${GMAP_KEY}
      INJECT_VIRTUAL_GALLERY_URL: ${VIRTUAL_GALLERY_URL}