# Customize this file to include compose configurations common to bluprints
version: '3'

services:
  backend:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${VANILLA_DIR}/scripts:/code/scripts
    networks:
      worker_net:
      ftp_net:
    depends_on:
      - neo4j
      # - ftp
      # - swaggerui
    environment:
      AUTH_ENABLE: 1
      AUTH_SERVICE: neo4j

      # # neo connection
      GRAPHDB_ENABLE: 1
      GRAPHDB_EXTERNAL: ${GRAPHDB_EXTERNAL}
      GRAPHDB_HOST: ${GRAPHDB_HOST}
      GRAPHDB_PORT: ${GRAPHDB_BOLT_PORT}
      GRAPHDB_PASSWORD: ${GRAPHDB_PASSWORD}

      CELERY_ENABLE: 1
      CELERY_EXTERNAL: ${CELERY_EXTERNAL}
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BROKER_HOST: ${CELERY_BROKER_HOST}
      CELERY_BROKER_PORT: ${CELERY_BROKER_PORT}
      CELERY_BACKEND: ${CELERY_BACKEND}
      CELERY_BACKEND_HOST: ${CELERY_BACKEND_HOST}
      CELERY_BACKEND_PORT: ${CELERY_BACKEND_PORT}

      SMTP_ADMIN: ${SMTP_ADMIN}
      SMTP_NOREPLY: ${SMTP_NOREPLY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  proxy:
    environment:
      SMTP_ADMIN: ${SMTP_ADMIN}

  neo4j:
    restart: on-failure:5
    volumes:
      - ${VANILLA_DIR}/data/graphdata:/data
    ports:
      - 7687:7687
    environment:
      # NEO4J_dbms_memory_pagecache_size: 1024M
      # NEO4J_dbms_memory_heap_maxSize: 2048M
      NEO4J_AUTH: neo4j/${GRAPHDB_PASSWORD}
      # NEO4J_dbms_allowFormatMigration: "true"

  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${SUBMODULE_DIR}/imedia-pipeline:/imedia-pipeline
      - /opt/idmt:/opt/idmt
      - ${VANILLA_DIR}/scripts:/code/scripts
      - ${VANILLA_DIR}/data/ssh:/home/developer/.ssh
    depends_on:
      - rabbit
      - mongodb
      - neo4j

    environment:
      AUTH_ENABLE: 1
      AUTH_SERVICE: neo4j

      # # neo connection
      GRAPHDB_ENABLE: 1
      GRAPHDB_EXTERNAL: ${GRAPHDB_EXTERNAL}
      GRAPHDB_HOST: ${GRAPHDB_HOST}
      GRAPHDB_PORT: ${GRAPHDB_BOLT_PORT}
      GRAPHDB_PASSWORD: ${GRAPHDB_PASSWORD}

      SMTP_ADMIN: ${SMTP_ADMIN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      # Used to manage analysis script on both prod and pre-prod
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}

  celeryui:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${VANILLA_DIR}/scripts:/code/scripts
    environment:

      CELERYUI_USER: imc
      CELERYUI_PASSWORD: d43WtSXe49

      AUTH_ENABLE: 1
      # putting this here because it should not be configurable in .env
      AUTH_SERVICE: neo4j

      # # neo connection
      GRAPHDB_ENABLE: 1
      GRAPHDB_EXTERNAL: ${GRAPHDB_EXTERNAL}
      GRAPHDB_HOST: ${GRAPHDB_HOST}
      GRAPHDB_PORT: ${GRAPHDB_BOLT_PORT}
      GRAPHDB_PASSWORD: ${GRAPHDB_PASSWORD}

    depends_on:
      - rabbit
      - mongodb
      - neo4j

  ftp:
    ports:
      - "21:21"
      - "30000-30019:30000-30019"
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/home/ftpusers/

  frontend:
    environment:
      ALLOW_PASSWORD_RESET: "true"
      ALLOW_REGISTRATION: "false"