# Customize this file to include compose configurations common to bluprints
version: "3"

services:
  backend:
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${VANILLA_DIR}/scripts:/code/scripts
    networks:
      ftp_net:
    environment:
      CATALOG_TIME_RANGE_FROM: ${CATALOG_TIME_RANGE_FROM}
      CATALOG_TIME_RANGE_TO: ${CATALOG_TIME_RANGE_TO}

  neo4j:
    volumes:
      - ${VANILLA_DIR}/data/graphdata:/data
    ports:
      - 7687:7687
      - 9090:${NEO4J_WEB_INTERFACE_PORT}

  rabbit:
    expose:
      - "15672"
    ports:
      - 15672:15672

  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/celery
    image: imediacities/celery:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${SUBMODULE_DIR}/imedia-pipeline:/imedia-pipeline
      - /opt/idmt:/opt/idmt
      - ${VANILLA_DIR}/scripts:/code/scripts
      - ${VANILLA_DIR}/data/ssh:/home/developer/.ssh

    environment:
      # Used to manage analysis script on both prod and pre-prod
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}

  flower:
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${VANILLA_DIR}/scripts:/code/scripts
      - ${VANILLA_DIR}/data/flower_db:${CELERYUI_DBDIR}

  ftp:
    ports:
      - "21:21"
      - "30000-30019:30000-30019"
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/home/ftpusers/
      - ${VANILLA_DIR}/data/ftp:/etc/pure-ftpd/passwd

  frontend:
    environment:
      INJECT_GMAP_KEY: ${GMAP_KEY}
      INJECT_VIRTUAL_GALLERY_URL: ${VIRTUAL_GALLERY_URL}
      INJECT_FRONTEND_LANG: ${FRONTEND_LANG}
      INJECT_FRONTEND_DISABLED_FILTERS: ${FRONTEND_DISABLED_FILTERS}
      INJECT_CATALOG_TIME_RANGE_FROM: ${CATALOG_TIME_RANGE_FROM}
      INJECT_CATALOG_TIME_RANGE_TO: ${CATALOG_TIME_RANGE_TO}
