# Customize this file to include compose configurations common to bluprints
version: "3"

services:
  backend:
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${VANILLA_DIR}/scripts:/code/scripts
    networks:
      ftp_net:

  neo4j:
    volumes:
      - ${VANILLA_DIR}/data/graphdata:/data
    ports:
      - 7687:7687
    #environment:
    #   NEO4J_unsupported_dbms_tx__log_fail__on__corrupted__log__files: "False"
    #   NEO4J_dbms_recovery_fail__on__missing__files: "False"
    #   NEO4J_dbms_memory_pagecache_size: 1024M
    #   NEO4J_dbms_memory_heap_maxSize: 2048M
    #   NEO4J_dbms_allowFormatMigration: "true"

  rabbit:
    expose:
      - "15672"
    ports:
      - 15672:15672

  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/celery
    image: imediacities/celery:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${SUBMODULE_DIR}/imedia-pipeline:/imedia-pipeline
      - /opt/idmt:/opt/idmt
      - ${VANILLA_DIR}/scripts:/code/scripts
      - ${VANILLA_DIR}/data/ssh:/home/developer/.ssh

    environment:
      # Used to manage analysis script on both prod and pre-prod
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}

  celeryui:
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/uploads
      - ${VANILLA_DIR}/scripts:/code/scripts
      - ${VANILLA_DIR}/data/flower_db:${CELERYUI_DBDIR}

  ftp:
    ports:
      - "21:21"
      - "30000-30019:30000-30019"
    volumes:
      - ${VANILLA_DIR}/data/imediastuff:/home/ftpusers/
      - ${VANILLA_DIR}/data/ftp:/etc/pure-ftpd/passwd

  frontend:
    environment:
      INJECT_GMAP_KEY: ${GMAP_KEY}
      INJECT_VIRTUAL_GALLERY_URL: ${VIRTUAL_GALLERY_URL}
