version: "3.8"

services:
  backend:
    volumes:
      - ${DATA_DIR}/imediastuff:/uploads
      - ${PROJECT_DIR}/scripts:/code/scripts

    environment:
      CATALOG_TIME_RANGE_FROM: ${CATALOG_TIME_RANGE_FROM}
      CATALOG_TIME_RANGE_TO: ${CATALOG_TIME_RANGE_TO}

  neo4j:
    volumes:
      - ${DATA_DIR}/graphdata:/data

  celery:
    build: ${PROJECT_DIR}/builds/celery
    image: imediacities/celery:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/imediastuff:/uploads
      - ${SUBMODULE_DIR}/imedia-pipeline:/imedia-pipeline
      - /opt/idmt:/opt/idmt
      - ${PROJECT_DIR}/scripts:/code/scripts
      - ${DATA_DIR}/ssh:/home/developer/.ssh

    environment:
      # Used to manage analysis script on both prod and pre-prod
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}

  flower:
    volumes:
      - ${DATA_DIR}/imediastuff:/uploads
      - ${PROJECT_DIR}/scripts:/code/scripts
      - ${DATA_DIR}/flower_db:${FLOWER_DBDIR}

  ftp:
    ports:
      - "21:21"
      - "30000-30019:30000-30019"
    volumes:
      - ${DATA_DIR}/imediastuff:/home/ftpusers/
      - ${DATA_DIR}/ftp:/etc/pure-ftpd/passwd

  frontend:
    environment:
      INJECT_GMAP_KEY: ${GMAP_KEY}
      INJECT_VIRTUAL_GALLERY_URL: ${VIRTUAL_GALLERY_URL}
      INJECT_FRONTEND_LANG: ${FRONTEND_LANG}
      INJECT_FRONTEND_DISABLED_FILTERS: ${FRONTEND_DISABLED_FILTERS}
      INJECT_CATALOG_TIME_RANGE_FROM: ${CATALOG_TIME_RANGE_FROM}
      INJECT_CATALOG_TIME_RANGE_TO: ${CATALOG_TIME_RANGE_TO}
