# Customize this file to include compose configurations common to bluprints
version: '3'

services:

  neo4j:
    # ports:
    #   - 9090:7474
    ports:
      - 9090:7473
    volumes:
      - letsencrypt_certs:/ssl
    environment:
      ACTIVATE: 1

  # Cloned from proxy service
  proxy-neo4j:
    build:
      context: ${SUBMODULE_DIR}/build-templates/proxy
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
        CURRENT_UID: ${CURRENT_UID}
    image: rapydo/proxy:${RAPYDO_VERSION}
    hostname: reverseproxy
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - ssl_dhparam:/etc/nginx/ssl/
    volumes:
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/confs/nginx-neo4j.conf:/etc/nginx/sites-enabled/production

    networks:
      proxy_net:
        aliases:
          - ${PROXY_HOST}
    ports:
      - ${PROXY_DEV_PORT}:${PROXY_DEV_PORT}   # 80 redirect
      - ${PROXY_PROD_PORT}:${PROXY_PROD_PORT} # 443 SSL
    environment:
      ACTIVATE: 1
      DOMAIN: ${PROJECT_DOMAIN}
      MODE: ${LETSENCRYPT_MODE}
      SMTP_ADMIN: ${SMTP_ADMIN}
      CURRENT_UID: ${CURRENT_UID}
    depends_on:
      - neo4j

  mongodb:
    environment:
      ACTIVATE: 0

  backend:
    environment:
      ACTIVATE: 0

  frontend:
    environment:
      ACTIVATE: 0

  ftp:
    environment:
      ACTIVATE: 0

  celery:
    environment:
      ACTIVATE: 0

  celeryui:
    environment:
      ACTIVATE: 0
