version: '3'
#######################
# Link services inside API

services:

  proxy:
    environment:
      ACTIVATE: 1
    volumes:
      - ../confs/nginx/production.conf:/etc/nginx/sites-enabled/production
    depends_on:
      - backend
      - frontend

  backend:
    environment:
      - APP_MODE=production
      - DEBUG_LEVEL=INFO
      - NGINX_ACTIVE=true
    networks:
      proxy_net:
        aliases:
          - ${FLASK_HOST}

  frontend:
    environment:
      APP_MODE: production
    networks:
      proxy_net:
        aliases:
          - html

  celery:
    environment:
      DEBUG_LEVEL: INFO
      ACTIVATE: 1
