version: '3'
#######################
# Link services inside API

services:

  proxy:
    environment:
      ACTIVATE: 1
    volumes:
      - ${SUBMODULE_DIR}/rapydo-confs/confs/nginx/production.conf:/etc/nginx/sites-enabled/production
    depends_on:
      - backend
      - frontend

  backend:
    environment:
      - APP_MODE=production
      - DEBUG_LEVEL=INFO
      - NGINX_ACTIVE=true
      - PYTHONPATH=/code
    networks:
      proxy_net:
        aliases:
          - ${FLASK_HOST}

  neo4j:
    ports:
      - 9090:7473
    volumes:
      - letsencrypt_certs:/ssl

  frontend:
    environment:
      - APP_MODE=production
      - APP_DEBUG=false 
    networks:
      proxy_net:
        aliases:
          - html

  celery:
    environment:
      DEBUG_LEVEL: INFO
      ACTIVATE: 1
