version: '3'
#######################
# Link services inside API

services:

  proxy:
    environment:
      ACTIVATE: 1
      SMTP_ADMIN: ${SMTP_ADMIN}
    volumes:
      # - ${SUBMODULE_DIR}/rapydo-confs/confs/nginx/production.conf:/etc/nginx/sites-enabled/production
      - ${SUBMODULE_DIR}/rapydo-confs/confs/nginx/production-a2.conf:/etc/nginx/sites-enabled/production
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/frontend:/modules
    depends_on:
      - backend
      - frontend

  backend:
    environment:
      APP_MODE: production
      DEBUG_LEVEL: INFO
      NGINX_ACTIVE: "True"
    networks:
      proxy_net:
        aliases:
          - ${FLASK_HOST}

  neo4j:
    ports:
      - 9090:7473
    volumes:
      - letsencrypt_certs:/ssl

  frontend:
    environment:
      APP_MODE: production
    networks:
      proxy_net:
        aliases:
          - html

  celery:
    environment:
      DEBUG_LEVEL: INFO
      APP_MODE: production
    depends_on:
      - rabbit
      - mongodb
      - neo4j

  celeryui:
    depends_on:
      - rabbit
      - mongodb
      - neo4j