
gdb:
  ports:
  - 9090:7474

#######################
# Link services inside API

backend:
  environment:
    BACKEND_AUTH_SERVICE: graphdb
  volumes:
    - ../imediastuff:/uploads
  links:
    - gdb:gdb