
gdb:
  ports:
  - 9090:7474
  - 7687:7687

#######################
# Link services inside API

backend:
  environment:
    DEBUG_LEVEL: INFO
    BACKEND_AUTH_SERVICE: graphdb
  volumes:
    - ../imediastuff:/uploads
  links:
    - gdb:gdb