definitions:
  Annotation:
    required:
      - motivation
      - target
      - body
    properties:
      motivation:
        type: string
        enum:
          - tagging
          - commenting
          - describing
          - identifying
          - classifying
          - replying
          - segmentation
      body:
        $ref: "#/definitions/Body"
      target:
        type: string
        pattern: "(item|shot|anno):[a-z0-9-]+"
      selector:
        $ref: "#/definitions/Selector"
      private:
        type: boolean
        default: false
      embargo:
        type: string
        format: date

  List:
    required:
      - name
      - description
    properties:
      name:
        type: string
      description:
        type: string

  Body:
    discriminator: type
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - ResourceBody
          - TextualBody
          - TVSBody

  ResourceBody:
    allOf:
      - $ref: "#/definitions/Body"
      - required:
          - source
        properties:
          source:
            $ref: "#/definitions/Source"
          spatial:
            $ref: "#/definitions/Spatial"
  TextualBody:
    allOf:
      - $ref: "#/definitions/Body"
      - required:
          - value
        properties:
          value:
            type: string
          language:
            type: string
            default: "en"
  TVSBody:
    allOf:
      - $ref: "#/definitions/Body"
      - required:
          - segments
        properties:
          segments:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              type: string
              pattern: "t=[0-9],[0-9]"
  Selector:
    required:
      - type
      - value
    properties:
      type:
        type: string
        enum:
          - FragmentSelector
          - AreaSelector
      value:
        type: string

  Source:
    required:
      - iri
      - name
    properties:
      iri:
        type: string
      name:
        type: string
      alternativesNames:
        $ref: "#/definitions/AlternativeNames"

  AlternativeNames:
    additionalProperties:
      type: string

  Spatial:
    required:
      - lat
      - long
    properties:
      lat:
        type: number
        format: double
      long:
        type: number
        format: double

  GeoDistance:
    required:
      - distance
      - location
    properties:
      distance:
        type: integer
        description: Distance in km
        minimum: 1
      location:
        $ref: "#/definitions/Spatial"
        description: Pin location

  SearchCriteria:
    properties:
      match:
        $ref: "#/definitions/SearchMatch"
      filter:
        $ref: "#/definitions/SearchFilter"

  AnnotationSearchCriteria:
    properties:
      type:
        type: string
      filter:
        properties:
          geo_distance:
            $ref: "#/definitions/GeoDistance"

  SearchMatch:
    required:
      - term
      - fields
    properties:
      term:
        type: string
      fields:
        type: array
        items:
          type: string
          enum:
            - title
            - contributor
            - keyword
            - description
        minItems: 1

  SearchFilter:
    properties:
      type:
        type: string
        enum:
          - all
          - video
          - image
      provider:
        type: string
      country:
        type: string
        description: production country, codelist iso3166-1
      yearfrom:
        description: production year range, start year of the range
        type: integer
        minimum: 1900
        maximum: 2000
      yearto:
        description: production year range, end year of the range, maximum=2000, yearto>=yearfrom
        type: integer
        minimum: 1900
        maximum: 2000
      iprstatus:
        description: IPR status
        type: string
        enum:
          - 01
          - 02
          - 03
          - 04
          - 05
          - 06
          - 07
          - 08
          - 09
          - 10
      terms:
        type: array
        items:
          required:
            - label
          properties:
            iri:
              type: string
            label:
              type: string
      geo_distance:
        $ref: "#/definitions/GeoDistance"
      annotated_by:
        type: string
        description: User's uuid

  VideoInRevision:
    description: Video under revision
    required:
      - "since"
      - "video"
      - "progress"
      - "state"
      - "assignee"
    properties:
      since:
        description: Date of start of a revision.
        type: string
        format: date
      video:
        description: Video under revision
        required:
          - uuid
          - title
        properties:
          uuid:
            type: string
          title:
            type: string
      progress:
        description: Progress of the revision in percentange
        type: integer
        format: int32
        minimum: 0
        maximum: 100
      state:
        description: Revision status
        type: string
        enum:
          - "R"
          - "W"
      assignee:
        description: assignee of the revision
        required:
          - uuid
          - name
        properties:
          uuid:
            type: string
          name:
            type: string
